language: csharp
mono: none
dotnet: 3.1
dist: trusty
sudo: false
install:
  - dotnet restore ./MintPlayer.AspNetCore.SitemapXml.sln
script:
  - dotnet build ./MintPlayer.AspNetCore.SitemapXml.sln
  - dotnet test ./MintPlayer.AspNetCore.SitemapXml/MintPlayer.AspNetCore.SitemapXml.csproj
cache:
  directories:
  - ./BuildPackages